image: docker:19

stages:
- test

variables:
  BUILD_VERSION: v0.4.0

Test C++ bindings:
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  stage: test
  image: registry.gitlab.com/pep10/libsim/emboost:${BUILD_VERSION}
  needs: []
  script:
    - source /emsdk/emsdk_env.sh
    - export CXX=$(which clang++)
    - export C=$(which clang)
    - (cd gen && python3 gen.py)
    - mkdir build && cd build
    - cmake ../
    - make -j20 && make test